server:
  port: 80


spring:
  application:
    name: cloud-order-server

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true
    #心跳检测与续约时间
    #开发时设置小点，保证服务关闭后能及时剔除服务
    #Eureka客户端向服务端发送心跳的间隔时间，单位为秒
    lease-renewal-interval-in-seconds: 2
    #Eureka服务端在收到最后一次心跳后等待时间上限，超时即剔除，单位为秒
    lease-expiration-duration-in-seconds: 2